{
  "openapi": "3.0.1",
  "info": {
    "title": "Controle de Acesso",
    "description": "\n# Introdução\n\nEsta página contém todos os métodos que permitem consultar os usuários ativos para alimentar sistemas de Wifi e catracas.\n\n\n### Quadro de Relacionamentos -JACAD\n<iframe style=\"border:none\" width=\"100%\" height=\"450\" src=\"https://whimsical.com/embed/JSZHN7TY25PZogto4GiP1D\"></iframe>\n \n## Segurança\n\nA API REST do JACAD utiliza o protocolo HTTPS para  uma  comunicação  criptografada, além  disso, todas as solicitações  na API são  obrigadas a informar  um  **token de  acesso** (Access Token) para  garantir a .\n\n### Obtendo  uma  Chave  de API\n\nPara  obter  um Token de  Acesso é necessário  se  autenticar  com  uma  **Chave  de API**. Você  pode  obter  sua  Chave  de API no painel  de  administração  da  plataforma SWA.JACAD.\n\nUma  Chave  de API tem o seguinte  formato:\n\n```json\n5837fa342c8a14c50c2d7c9a73369dce\n```\n\nUma  chave  de API deve  ser  definido  na  plataforma SWA.JACAD para  autenticação  na API.\n\nNavegue  até:`Integrações` > `API de  Integrações` > `Tokens de  Acesso` > `Cadastro  de Token de  Acesso`.\n\n1. Clique em  **Inserir**.\n2. Selecione  um  usuário.\n3. Insira a data de  vigência do token ou  marque a flag para  não  validar  datas.\n4. Clique em  salvar  para  gerar  automaticamente  um Token.\n\n**Nota:** É necessário  possuir  privilégios  de  administrador  para  obter  uma  chave  de API.\n\n![SWA.JACAD Desktop](/gerando-token.png \"Gerando Token de  acesso\")\n\n\n### Aviso\n\nTokens de API podem  representar  um  risco  de  segurança  para  sua  organização  se  usados  por  uma  pessoa  não  autorizada. Certifique-se  de  mantê-los  seguros, exclua as chaves  antigas e substitua-as em  seu  sistema  se  suspeitar  de  alguma  violação  de  segurança.\n\n> Você  pode  entrar  em  contato  conosco  para  obter  suporte  adicional.\n\n## Rate Limit\n\nTokens de requisição são uma abordagem eficiente para gerenciar o acesso a recursos, impedindo abusos e assegurando uma distribuição equitativa. No seu sistema, há dois principais filtros de controle de tokens:\n\n### Bloqueio Técnico:\n\n- **Quantidade Inicial:** 10 tokens por IP.\n- **Taxa de Recarga:** 1 token por segundo.\n- **Restrição:** Cada IP pode fazer 10 requisições por segundo. Após atingir esse limite, é necessário aguardar até que novos tokens sejam disponibilizados.\n\n### Filtro de Negócio:\n\n- **Quantidade Inicial:** Definida pelo usuário (por exemplo, 1000 tokens).\n- **Taxa de Recarga:** Recarregado a cada 1 hora.\n- **Restrição Adicional:** Se todos os tokens forem usados antes do período de uma hora, a recarga só ocorre após o término desse período, contado a partir do momento da última recarga. Por exemplo, se 1000 tokens forem usados em 55 minutos, a próxima recarga só ocorrerá 5 minutos após a última recarga.\n\nEste sistema oferece um equilíbrio entre acesso rápido (Bloqueio Técnico) e controle de uso a longo prazo (Filtro de Negócio), garantindo uma distribuição justa e evitando abusos.\n\n\n### Configuração do Controle de Requisições:\n\nNavegue  até:`Preferências` > `Segurança` > `Políticas de Segurança`.\n\nEm nossa plataforma, oferecemos total controle sobre como gerenciar suas requisições. Aqui está um guia simples para configurar o Filtro de Negócio:\n\n#### 1. Habilitar Controle de Requisições:\n\n- Para começar, marque a caixa de seleção \"Habilitar Controle de Requisições\". Isso permite que você personalize a quantidade máxima de requisições.\n\n- [ ] Habilitar Controle de Requisições\n\n#### 2. Definir Quantidade Máxima (Padrão: 1000 por Hora):\n- Abaixo da opção habilitar, você encontrará um campo para inserir a quantidade desejada de tokens. O valor padrão é 1000 por hora.\n\nAo marcar a opção e inserir sua preferência, você tem o poder de moldar como deseja que o Filtro de Negócio funcione para você.\n\nLembre-se: Se não desejar modificar, a configuração padrão de 1000 por hora permanecerá em vigor.\n\n![SWA.JACAD Desktop](/configurando-token.png \"Configurando entrada maxima de tokens\")\n\n\n## Jacad API Rest\n\nA API utiliza  os  princípios  das APIs REST, permitindo  que  os  desenvolvedores  realizem  consultas  na  plataforma SWA.JACAD utilizando o protocolo HTTP.\n\nUse uma  solicitação  **GET**  para  recuperar  informações, um  **POST**  para  criar  ou  atualizar e um  **DELETE**  para remover uma  informação.\n\n### Bearer Token (JWT)\n\nTodas as solicitações  de API requerem  um token de autorização para  validar a autenticidade e indicar  ao  sistema  quais  módulos, operações e recursos o usuário  pode  acessar. \n\nO Token JWT deve ser informado no cabeçalho (header) da solicitação como no formato abaixo:\n\n```json\nAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c\n```\n\n**Nota:** O token JWT é obtido  após  realizar a autenticação  na API.\n\n\n\n\n### Respostas  de  Erros\n\nA API usa  códigos  de status HTTP padrão  para  indicar o sucesso  ou a falha  como  acontece  com  qualquer  resposta  de API, seu  cliente  deve  estar  preparado  para  lidar  com  erros  de  resposta. Normalmente, o corpo  da  resposta  será JSON no seguinte  formato:\n\n```json\n{\n\t\"timestamp\": \"2023-09-19T16:23:53-0300\",\n\t\"message\": \"Failed to convert property 'anoConsolidacao'\",\n\t\"details\": \"/api/v4/resource\",\n\t\"errorCode\": {\n\t\t\"code\": \"VFLD01\",\n\t\t\"desc\": \"Valor informado  inválido\"\n\t},\n\t\"validationErrors\": [\n\t\t{\n\t\t\t\"field\": \"anoConsolidacao\",\n\t\t\t\"rejectedValue\": \"2022-ASDF\",\n\t\t\t\"message\": \"Failed to convert property 'anoConsolidacao'\"\n\t\t}\n\t]\n}\n\n```\n\n### Código  de Status\n\n| CÓDIGO | DESCRIÇÃO | NOTA |\n| ------ | ------ | ------ |\n| 200 | OK | A requisição  foi  bem  sucedida. |\n| 201 | Created | Os  dados  foram  gravados  com  sucesso no sistema |\n| 400 | Bad Request | A solicitação  não  pôde  ser  compreendida  pelo  servidor. Os  parâmetros  recebidos  podem  não  ser  válidos |\n| 401 | Unauthorized | As credenciais  fornecidas, se  houver, não  são  suficientes  para  acessar o recurso |\n| 403 | Forbidden | As credenciais  fornecidas  não  possui  permissão  para  acessar o recurso. |\n| 404 | Not Found | A informação  requerida  não  foi  encontrada |\n| 422 | Unprocessable Entity | Não  foi  possível  processar a informação  devido a restrições  de  uso. |\n| 500 | Server Error | Erro  inesperado, ocorreu  algum  erro  interno no servidor |\n| 429 | Too Many Requests | Limite de requisições |",
    "termsOfService": "https://www.swa.com.br/termo-de-uso/",
    "contact": {
      "name": "Suporte",
      "url": "https://ajuda.jacad.com.br",
      "email": "suporte@swa.com.br"
    },
    "version": "v3.1.60.410"
  },
  "servers": [
    {
      "url": "https://insted-developer.jacad.com.br",
      "description": "Generated server url"
    }
  ],
  "security": [
    {
      "Access Token": []
    }
  ],
  "tags": [
    {
      "name": "Autenticação"
    }
  ],
  "paths": {
    "/api/v1/auth/token": {
      "post": {
        "tags": [
          "Autenticação"
        ],
        "summary": "Realiza a autenticação via token",
        "description": "Autentica o usuário a partir de um token de acesso a API cadastrado através do sistema acadêmico (desktop)",
        "operationId": "token",
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": true,
            "schema": {
              "maximum": 40,
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserInfo"
                }
              }
            }
          },
          "400": {
            "description": "Solicitação inválida, contém erros de tipos ou de formatação",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.108+00:00",
                  "message": "Um ou mais campos estão inválidos",
                  "details": "/api/v1/resource",
                  "errorCode": {
                    "code": "VFLD01",
                    "desc": "Valor informado inválido"
                  },
                  "validationErrors": [
                    {
                      "field": "anoConsolidacao",
                      "rejectedValue": "202A",
                      "message": "Falha ao converter a propriedade 'anoConsolidacao'"
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Acesso negado, O usuário não está autenticado ou possui credenciais inválidas",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.108+00:00",
                  "message": "É necessário estar autenticado para acessar este recurso",
                  "details": "/api/v1/resource",
                  "errorCode": {
                    "code": "EXPTK01",
                    "desc": "Token inválido ou expirado"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Proibido, o usuário autenticado não possui a permissão de acesso para o recurso solicitado.",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.108+00:00",
                  "message": "Voce nao tem permissao para acessar este recurso",
                  "details": "/api/v1/resource"
                }
              }
            }
          },
          "404": {
            "description": "Recurso não encontrado",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.108+00:00",
                  "message": "Registro de código '123' não encontrado",
                  "details": "/api/v1/resource"
                }
              }
            }
          },
          "500": {
            "description": "Erro inesperado, ocorreu algum erro interno no servidor",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.108+00:00",
                  "message": "Erro desconhecido",
                  "details": "/api/v1/resource"
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/controle-acesso/wifi/ativos": {
      "get": {
        "tags": [
          "Controle de Acesso"
        ],
        "summary": "Integrações - Usuários ativos para redes WIFI (logins e senhas)",
        "description": "Este método retorna todos os alunos, funcionários e professores <strong>ATIVOS</strong> na instituição neste momento que tenham login e senha preenchidos em seu perfil.<br/>Este método trará somente alunos com matrícula <strong>ATIVA</strong> num período letivo ABERTO, professores que estejam lecionando numa turma ATIVA num período letivo ABERTO e funcionários que não sejam professores e que tenham o seu status com <strong>ATIVO</strong>.",
        "operationId": "listaPessoasAtivas",
        "parameters": [
          {
            "name": "pageSize",
            "in": "query",
            "description": "Total de registros que serão retornados a cada consulta (máximo de 500)",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            },
            "example": 100
          },
          {
            "name": "currentPage",
            "in": "query",
            "description": "Página atual dos resultados",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int32"
            },
            "example": 1
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PaginationPessoaAtivaRestPage"
                }
              }
            }
          },
          "400": {
            "description": "Solicitação inválida, contém erros de tipos ou de formatação",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.111+00:00",
                  "message": "Um ou mais campos estão inválidos",
                  "details": "/api/v1/resource",
                  "errorCode": {
                    "code": "VFLD01",
                    "desc": "Valor informado inválido"
                  },
                  "validationErrors": [
                    {
                      "field": "anoConsolidacao",
                      "rejectedValue": "202A",
                      "message": "Falha ao converter a propriedade 'anoConsolidacao'"
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Acesso negado, O usuário não está autenticado ou possui credenciais inválidas",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.112+00:00",
                  "message": "É necessário estar autenticado para acessar este recurso",
                  "details": "/api/v1/resource",
                  "errorCode": {
                    "code": "EXPTK01",
                    "desc": "Token inválido ou expirado"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Proibido, o usuário autenticado não possui a permissão de acesso para o recurso solicitado.",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.112+00:00",
                  "message": "Voce nao tem permissao para acessar este recurso",
                  "details": "/api/v1/resource"
                }
              }
            }
          },
          "404": {
            "description": "Recurso não encontrado",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.112+00:00",
                  "message": "Registro de código '123' não encontrado",
                  "details": "/api/v1/resource"
                }
              }
            }
          },
          "500": {
            "description": "Erro inesperado, ocorreu algum erro interno no servidor",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.112+00:00",
                  "message": "Erro desconhecido",
                  "details": "/api/v1/resource"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/controle-acesso/matriculas-entrada-saida": {
      "get": {
        "tags": [
          "Controle de Acesso"
        ],
        "summary": "Integrações - Consulta de Alunos para a Gestão de Entrada e Saída",
        "description": "Esse método retorna somente matrículas ATIVAS, de turmas ABERTAS e de períodos letivos ABERTOS e do ano ATUAL",
        "operationId": "listEntradaSaida",
        "parameters": [
          {
            "name": "descricao",
            "in": "query",
            "description": "Termo para filtrar RA, Nome do Aluno, Nome da Turma ou Curso",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": "Administração"
          },
          {
            "name": "pageSize",
            "in": "query",
            "description": "Total de registros que serão retornados a cada consulta (máximo de 500)",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            },
            "example": 100
          },
          {
            "name": "currentPage",
            "in": "query",
            "description": "Página atual dos resultados",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int32"
            },
            "example": 1
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PaginationMatriculaEntradaSaidaDtoResPage"
                }
              }
            }
          },
          "400": {
            "description": "Solicitação inválida, contém erros de tipos ou de formatação",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.113+00:00",
                  "message": "Um ou mais campos estão inválidos",
                  "details": "/api/v1/resource",
                  "errorCode": {
                    "code": "VFLD01",
                    "desc": "Valor informado inválido"
                  },
                  "validationErrors": [
                    {
                      "field": "anoConsolidacao",
                      "rejectedValue": "202A",
                      "message": "Falha ao converter a propriedade 'anoConsolidacao'"
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Acesso negado, O usuário não está autenticado ou possui credenciais inválidas",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.113+00:00",
                  "message": "É necessário estar autenticado para acessar este recurso",
                  "details": "/api/v1/resource",
                  "errorCode": {
                    "code": "EXPTK01",
                    "desc": "Token inválido ou expirado"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Proibido, o usuário autenticado não possui a permissão de acesso para o recurso solicitado.",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.113+00:00",
                  "message": "Voce nao tem permissao para acessar este recurso",
                  "details": "/api/v1/resource"
                }
              }
            }
          },
          "404": {
            "description": "Recurso não encontrado",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.113+00:00",
                  "message": "Registro de código '123' não encontrado",
                  "details": "/api/v1/resource"
                }
              }
            }
          },
          "500": {
            "description": "Erro inesperado, ocorreu algum erro interno no servidor",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.113+00:00",
                  "message": "Erro desconhecido",
                  "details": "/api/v1/resource"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/controle-acesso/catraca": {
      "get": {
        "tags": [
          "Controle de Acesso"
        ],
        "summary": "Integrações - Usuários ativos para acesso as catracas",
        "description": "Este método retorna todos os alunos, funcionários e professores <strong>ATIVOS</strong> na instituição que podem passar pelas catracas. Regras da consulta:<br/>Somente alunos com matrícula <strong>ATIVA</strong> num período letivo ABERTO e marcado como atual.<br/>Somente professores que estejam lecionando numa turma ATIVA num período letivo ABERTO e marcado como atual.<br/>Somente funcionários que não sejam professores e que tenham o seu status como <strong>ATIVO</strong>.",
        "operationId": "listPessoasAtivasCatraca",
        "parameters": [
          {
            "name": "pageSize",
            "in": "query",
            "description": "Total de registros que serão retornados a cada consulta (máximo de 500)",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            },
            "example": 100
          },
          {
            "name": "currentPage",
            "in": "query",
            "description": "Página atual dos resultados",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int32"
            },
            "example": 1
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PaginationUsuarioAtivoCatracaRestPage"
                }
              }
            }
          },
          "400": {
            "description": "Solicitação inválida, contém erros de tipos ou de formatação",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.115+00:00",
                  "message": "Um ou mais campos estão inválidos",
                  "details": "/api/v1/resource",
                  "errorCode": {
                    "code": "VFLD01",
                    "desc": "Valor informado inválido"
                  },
                  "validationErrors": [
                    {
                      "field": "anoConsolidacao",
                      "rejectedValue": "202A",
                      "message": "Falha ao converter a propriedade 'anoConsolidacao'"
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Acesso negado, O usuário não está autenticado ou possui credenciais inválidas",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.115+00:00",
                  "message": "É necessário estar autenticado para acessar este recurso",
                  "details": "/api/v1/resource",
                  "errorCode": {
                    "code": "EXPTK01",
                    "desc": "Token inválido ou expirado"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Proibido, o usuário autenticado não possui a permissão de acesso para o recurso solicitado.",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.115+00:00",
                  "message": "Voce nao tem permissao para acessar este recurso",
                  "details": "/api/v1/resource"
                }
              }
            }
          },
          "404": {
            "description": "Recurso não encontrado",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.115+00:00",
                  "message": "Registro de código '123' não encontrado",
                  "details": "/api/v1/resource"
                }
              }
            }
          },
          "500": {
            "description": "Erro inesperado, ocorreu algum erro interno no servidor",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.115+00:00",
                  "message": "Erro desconhecido",
                  "details": "/api/v1/resource"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/controle-acesso/catraca/usuarios": {
      "get": {
        "tags": [
          "Controle de Acesso"
        ],
        "summary": "Integrações - Usuários, Professores e Funcionários para acesso as catracas",
        "description": "Retorna <ul><li><b>Alunos</b> com matrícula ativa no periodo atual.</li><li><b>Funcionários</b> ativos que não são professores.</li><li><b>Professores</b> com perfil funcionário ativo.</li></ul>",
        "operationId": "listaUsuarioAcessoCatraca",
        "parameters": [
          {
            "name": "pageSize",
            "in": "query",
            "description": "Total de registros que serão retornados a cada consulta (máximo de 500)",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            },
            "example": 100
          },
          {
            "name": "currentPage",
            "in": "query",
            "description": "Página atual dos resultados",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int32"
            },
            "example": 1
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PaginationUsuarioAtivoCatracaRestPage"
                }
              }
            }
          },
          "400": {
            "description": "Solicitação inválida, contém erros de tipos ou de formatação",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.117+00:00",
                  "message": "Um ou mais campos estão inválidos",
                  "details": "/api/v1/resource",
                  "errorCode": {
                    "code": "VFLD01",
                    "desc": "Valor informado inválido"
                  },
                  "validationErrors": [
                    {
                      "field": "anoConsolidacao",
                      "rejectedValue": "202A",
                      "message": "Falha ao converter a propriedade 'anoConsolidacao'"
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Acesso negado, O usuário não está autenticado ou possui credenciais inválidas",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.117+00:00",
                  "message": "É necessário estar autenticado para acessar este recurso",
                  "details": "/api/v1/resource",
                  "errorCode": {
                    "code": "EXPTK01",
                    "desc": "Token inválido ou expirado"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Proibido, o usuário autenticado não possui a permissão de acesso para o recurso solicitado.",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.117+00:00",
                  "message": "Voce nao tem permissao para acessar este recurso",
                  "details": "/api/v1/resource"
                }
              }
            }
          },
          "404": {
            "description": "Recurso não encontrado",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.117+00:00",
                  "message": "Registro de código '123' não encontrado",
                  "details": "/api/v1/resource"
                }
              }
            }
          },
          "500": {
            "description": "Erro inesperado, ocorreu algum erro interno no servidor",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.117+00:00",
                  "message": "Erro desconhecido",
                  "details": "/api/v1/resource"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/auth/security/access-token": {
      "get": {
        "tags": [
          "Access Token"
        ],
        "summary": "Obter dados",
        "description": "Retorna os dados de um token de acesso.",
        "operationId": "obterDadosAccessToken",
        "parameters": [
          {
            "name": "accessToken",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "400": {
            "description": "Solicitação inválida, contém erros de tipos ou de formatação",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.119+00:00",
                  "message": "Um ou mais campos estão inválidos",
                  "details": "/api/v1/resource",
                  "errorCode": {
                    "code": "VFLD01",
                    "desc": "Valor informado inválido"
                  },
                  "validationErrors": [
                    {
                      "field": "anoConsolidacao",
                      "rejectedValue": "202A",
                      "message": "Falha ao converter a propriedade 'anoConsolidacao'"
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Acesso negado, O usuário não está autenticado ou possui credenciais inválidas",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.119+00:00",
                  "message": "É necessário estar autenticado para acessar este recurso",
                  "details": "/api/v1/resource",
                  "errorCode": {
                    "code": "EXPTK01",
                    "desc": "Token inválido ou expirado"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Proibido, o usuário autenticado não possui a permissão de acesso para o recurso solicitado.",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.119+00:00",
                  "message": "Voce nao tem permissao para acessar este recurso",
                  "details": "/api/v1/resource"
                }
              }
            }
          },
          "404": {
            "description": "Recurso não encontrado",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.119+00:00",
                  "message": "Registro de código '123' não encontrado",
                  "details": "/api/v1/resource"
                }
              }
            }
          },
          "500": {
            "description": "Erro inesperado, ocorreu algum erro interno no servidor",
            "content": {
              "application/json": {
                "example": {
                  "timestamp": "2026-09-01T22:55:19.119+00:00",
                  "message": "Erro desconhecido",
                  "details": "/api/v1/resource"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "GrantedAuthority": {
        "type": "object",
        "properties": {
          "authority": {
            "type": "string"
          }
        }
      },
      "IUsuario": {
        "type": "object"
      },
      "Org": {
        "type": "object",
        "properties": {
          "id_org": {
            "type": "integer",
            "format": "int32"
          },
          "id_usuario_criacao": {
            "type": "integer",
            "format": "int32"
          },
          "id_usuario_alteracao": {
            "type": "integer",
            "format": "int32"
          },
          "data_criacao": {
            "type": "string",
            "format": "date-time"
          },
          "data_alteracao": {
            "type": "string",
            "format": "date-time"
          },
          "buscaIndexada": {
            "type": "boolean"
          },
          "idOrg": {
            "type": "integer",
            "format": "int32"
          },
          "idCliente": {
            "type": "integer",
            "format": "int32"
          },
          "descricao": {
            "type": "string"
          },
          "imagem": {
            "type": "string"
          },
          "nomeFantasia": {
            "type": "string"
          },
          "nomeComercial": {
            "type": "string"
          },
          "nomeComplementar": {
            "type": "string"
          },
          "nomePortalDiplomado": {
            "type": "string"
          },
          "nomeReduzido": {
            "type": "string"
          },
          "endereco": {
            "type": "string"
          },
          "cnpj": {
            "type": "string"
          },
          "inscricao": {
            "type": "string"
          },
          "enderecoFone": {
            "type": "string"
          },
          "pracaPagamento": {
            "type": "string"
          },
          "cep": {
            "type": "string"
          },
          "cidade": {
            "type": "string"
          },
          "inscricaoMunicipal": {
            "type": "string"
          },
          "diretorGeral": {
            "type": "string",
            "deprecated": true
          },
          "cssPortais": {
            "type": "string"
          },
          "secretariaAcademica": {
            "type": "string",
            "deprecated": true
          },
          "idPerfilDiretor": {
            "type": "integer",
            "format": "int32"
          },
          "portariaDiretor": {
            "type": "string"
          },
          "get_nomeDiretor": {
            "type": "string"
          },
          "get_sexoDiretor": {
            "type": "string"
          },
          "idPerfilSecretariaAcademica": {
            "type": "integer",
            "format": "int32"
          },
          "portariaSecretariaAcademica": {
            "type": "string"
          },
          "get_nomeSecretariaAcademica": {
            "type": "string"
          },
          "get_sexoSecretariaAcademica": {
            "type": "string"
          },
          "portariaCredenciamento": {
            "type": "string"
          },
          "website": {
            "type": "string"
          },
          "idCidadeNRE": {
            "type": "integer",
            "format": "int32"
          },
          "idPerfilDiretorAcademico": {
            "type": "integer",
            "format": "int32"
          },
          "get_nomeDiretorAcademico": {
            "type": "string"
          },
          "portariaDiretorAcademico": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "idPerfilResponsavelFinanceiro": {
            "type": "integer",
            "format": "int32"
          },
          "get_nomeResponsavelFinanceiro": {
            "type": "string"
          },
          "get_sexoResponsavelFinanceiro": {
            "type": "string"
          },
          "numero": {
            "type": "string"
          },
          "logradouro": {
            "type": "string"
          },
          "bairro": {
            "type": "string"
          },
          "idPerfilViceDiretor": {
            "type": "integer",
            "format": "int32"
          },
          "get_nomePerfilViceDiretor": {
            "type": "string"
          },
          "nomePortal": {
            "type": "string"
          },
          "idPerfilResposavelCertificacao": {
            "type": "integer",
            "format": "int32"
          },
          "get_nomePerfilResposavelCertificacao": {
            "type": "string"
          },
          "portariaCertificacao": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "idEmpresa": {
            "type": "integer",
            "format": "int32"
          },
          "codigoInep": {
            "type": "string"
          },
          "idPerfilRespLivroRegistro": {
            "type": "integer",
            "format": "int32"
          },
          "get_nomePerfilRespLivroRegistro": {
            "type": "string"
          },
          "getiDouNumeroMatriculaRespLivReg": {
            "type": "string"
          },
          "modeloNegocio": {
            "type": "string"
          },
          "idPerfilSecretariaDiplomaDigital": {
            "type": "integer",
            "format": "int32"
          },
          "portariaSecretariaDiplomaDigital": {
            "type": "string"
          },
          "idPerfilDiretorDiploma": {
            "type": "integer",
            "format": "int32"
          },
          "portariaDiretorDiploma": {
            "type": "string"
          },
          "funcaoDiretorDiploma": {
            "type": "string"
          },
          "idPerfilSecretariaDiploma": {
            "type": "integer",
            "format": "int32"
          },
          "portariaSecretariaDiploma": {
            "type": "string"
          },
          "funcaoSecretariaDiploma": {
            "type": "string"
          },
          "get_descricaoCliente": {
            "type": "string"
          },
          "ignorarLog": {
            "type": "boolean"
          },
          "usuario": {
            "$ref": "#/components/schemas/IUsuario"
          },
          "newObjectInCache": {
            "type": "boolean"
          }
        }
      },
      "TableEmailTag": {
        "type": "object",
        "properties": {
          "tag": {
            "type": "string"
          },
          "descricao": {
            "type": "string"
          },
          "exemplo": {
            "type": "string"
          }
        }
      },
      "UserInfo": {
        "type": "object",
        "properties": {
          "login": {
            "type": "string"
          },
          "token": {
            "type": "string"
          },
          "expiresIn": {
            "type": "integer",
            "format": "int64"
          },
          "deviceDetails": {
            "type": "string"
          },
          "idUsuario": {
            "type": "integer",
            "format": "int32"
          },
          "status": {
            "type": "string"
          },
          "idOrg": {
            "type": "integer",
            "format": "int32"
          },
          "idCliente": {
            "type": "integer",
            "format": "int32"
          },
          "idGrupoUsuario": {
            "type": "integer",
            "format": "int32"
          },
          "moduloID": {
            "type": "string"
          },
          "tipoGrupoUsuario": {
            "type": "string"
          },
          "nomeComercial": {
            "type": "string"
          },
          "descOrg": {
            "type": "string"
          },
          "modeloNegocio": {
            "type": "string"
          },
          "grupoUsuario": {
            "type": "string"
          },
          "usuarioDirector": {
            "type": "string"
          },
          "modulos": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "orgs": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Org"
            }
          },
          "usuario": {
            "$ref": "#/components/schemas/UsuarioPortal"
          },
          "org": {
            "$ref": "#/components/schemas/Org"
          }
        }
      },
      "UsuarioPortal": {
        "type": "object",
        "properties": {
          "id_org": {
            "type": "integer",
            "format": "int32"
          },
          "id_usuario_criacao": {
            "type": "integer",
            "format": "int32"
          },
          "id_usuario_alteracao": {
            "type": "integer",
            "format": "int32"
          },
          "data_criacao": {
            "type": "string",
            "format": "date-time"
          },
          "data_alteracao": {
            "type": "string",
            "format": "date-time"
          },
          "buscaIndexada": {
            "type": "boolean"
          },
          "idUsuario": {
            "type": "integer",
            "format": "int32"
          },
          "idGrupoUsuario": {
            "type": "integer",
            "format": "int32"
          },
          "nome": {
            "type": "string"
          },
          "forcarAlterarSenha": {
            "type": "integer",
            "format": "int32"
          },
          "senha": {
            "type": "string"
          },
          "descricao": {
            "type": "string"
          },
          "token": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "lookAndFeel": {
            "type": "string"
          },
          "skinBordas": {
            "type": "integer",
            "format": "int32"
          },
          "flagAcessoTodasContas": {
            "type": "integer",
            "format": "int32"
          },
          "usuarioWebService": {
            "type": "integer",
            "format": "int32"
          },
          "idIntegracao": {
            "type": "integer",
            "format": "int32"
          },
          "isUsuarioPolo": {
            "type": "integer",
            "format": "int32"
          },
          "dataUltimaAlteracaoSenha": {
            "type": "string",
            "format": "date-time"
          },
          "papelPolo": {
            "type": "string"
          },
          "get_nomeGrupoUsuario": {
            "type": "string"
          },
          "get_tipoGrupoUsuario": {
            "type": "string"
          },
          "idFuncionario": {
            "type": "integer",
            "format": "int32"
          },
          "get_funcionario": {
            "type": "string"
          },
          "get_emailEmpresa": {
            "type": "string"
          },
          "get_senhaEmailEmpresa": {
            "type": "string"
          },
          "get_idSetor": {
            "type": "integer",
            "format": "int32"
          },
          "get_idPerfil": {
            "type": "integer",
            "format": "int32"
          },
          "get_nomePerfil": {
            "type": "string"
          },
          "get_idCliente": {
            "type": "integer",
            "format": "int32"
          },
          "idUnidadeFisica": {
            "type": "integer",
            "format": "int32",
            "deprecated": true
          },
          "get_nomeUnidadeFisica": {
            "type": "string"
          },
          "desabilitarAcessoLogarComoNosPortais": {
            "type": "integer",
            "format": "int32"
          },
          "usuarioGlobalConfiguracao": {
            "type": "integer",
            "format": "int32"
          },
          "usuarioRemoto": {
            "$ref": "#/components/schemas/UsuarioSuporteBean"
          },
          "idCliente": {
            "type": "integer",
            "format": "int32"
          },
          "email": {
            "type": "string"
          },
          "emailStatus": {
            "type": "string"
          },
          "emailMotivoInvalido": {
            "type": "string"
          },
          "emailCodigoConfirmacao": {
            "type": "string"
          },
          "celular": {
            "type": "string"
          },
          "orgs": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Org"
            }
          },
          "permissoes": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/GrantedAuthority"
            }
          },
          "props": {
            "type": "object",
            "additionalProperties": {
              "type": "object"
            }
          },
          "enabled": {
            "type": "boolean"
          },
          "roles": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "authorities": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/GrantedAuthority"
            }
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "accountNonExpired": {
            "type": "boolean"
          },
          "accountNonLocked": {
            "type": "boolean"
          },
          "credentialsNonExpired": {
            "type": "boolean"
          },
          "emailDestinatario": {
            "type": "string"
          },
          "emailIdPerfil": {
            "type": "integer",
            "format": "int32"
          },
          "emailNomeDestinatario": {
            "type": "string"
          },
          "coreTagsPessoaFisica": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/TableEmailTag"
            }
          },
          "ignorarLog": {
            "type": "boolean"
          },
          "usuario": {
            "$ref": "#/components/schemas/IUsuario"
          },
          "newObjectInCache": {
            "type": "boolean"
          }
        }
      },
      "UsuarioSuporteBean": {
        "type": "object",
        "properties": {
          "idUsuarioDirector": {
            "type": "integer",
            "format": "int32"
          },
          "nome": {
            "type": "string"
          },
          "authToken": {
            "type": "string"
          },
          "dataLoginRemoto": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "Page": {
        "type": "object",
        "properties": {
          "pageSize": {
            "type": "integer",
            "format": "int32"
          },
          "currentPage": {
            "type": "integer",
            "format": "int32"
          },
          "totalElements": {
            "type": "integer",
            "format": "int32"
          },
          "totalPages": {
            "type": "integer",
            "format": "int32"
          },
          "ignoreFetching": {
            "type": "boolean"
          }
        }
      },
      "PaginationPessoaAtivaRestPage": {
        "type": "object",
        "properties": {
          "page": {
            "$ref": "#/components/schemas/Page"
          },
          "elements": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PessoaAtivaRest"
            }
          }
        }
      },
      "PessoaAtivaRest": {
        "type": "object",
        "properties": {
          "idPerfil": {
            "type": "integer",
            "format": "int32"
          },
          "tipo": {
            "type": "string"
          },
          "nome": {
            "type": "string"
          },
          "login": {
            "type": "string"
          },
          "senha": {
            "type": "string"
          },
          "ignorarLog": {
            "type": "boolean"
          }
        }
      },
      "MatriculaEntradaSaidaDtoRes": {
        "type": "object",
        "properties": {
          "ra": {
            "type": "string"
          },
          "nome": {
            "type": "string"
          },
          "turma": {
            "type": "string"
          },
          "periodoLetivo": {
            "type": "string"
          },
          "cursoBase": {
            "type": "string"
          },
          "idAluno": {
            "type": "integer",
            "format": "int32"
          },
          "idPerfil": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "PaginationMatriculaEntradaSaidaDtoResPage": {
        "type": "object",
        "properties": {
          "page": {
            "$ref": "#/components/schemas/Page"
          },
          "elements": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/MatriculaEntradaSaidaDtoRes"
            }
          }
        }
      },
      "PaginationUsuarioAtivoCatracaRestPage": {
        "type": "object",
        "properties": {
          "page": {
            "$ref": "#/components/schemas/Page"
          },
          "elements": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/UsuarioAtivoCatracaRest"
            }
          }
        }
      },
      "UsuarioAtivoCatracaRest": {
        "type": "object",
        "properties": {
          "contador": {
            "type": "integer",
            "format": "int32"
          },
          "idPerfil": {
            "type": "integer",
            "format": "int32"
          },
          "tipo": {
            "type": "string"
          },
          "nome": {
            "type": "string"
          },
          "login": {
            "type": "string"
          },
          "sexo": {
            "type": "string"
          },
          "cpf": {
            "type": "string"
          },
          "ra": {
            "type": "string"
          },
          "cursoIngresso": {
            "type": "string"
          },
          "ignorarLog": {
            "type": "boolean"
          }
        }
      }
    },
    "securitySchemes": {
      "Access Token": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header"
      }
    }
  }
}